In [1]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 데이터 준비
url = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
bt = pd.read_csv(url)

print(bt.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [3]:
# 종속변수, 독립변수
cause = bt[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
effect = bt[['medv']]
print(cause.shape, effect.shape)

(506, 13) (506, 1)


In [4]:
# 2. 모델 구조 만들기
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X) #X인풋을 받는다
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss = 'mse')

In [5]:
# 모델 구조 확인
model.summary() # 13개입력받았음, 2번째-> 10개입력받아서 1개layer받는모델추가
# dense_2 항이 10개 b가 1개
# inputLayer 14개 가중치가 필요, dense_2 -> 14*10개 140개 가중치

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [8]:
# 3. 데이터로 모델 학습(FIT)
model.fit(cause, effect, epochs=1000, verbose=0)
model.fit(cause, effect, epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 6ms/step - loss: 16.7954
Epoch 2/100
16/16 [==============================] - 0s 5ms/step - loss: 15.5090
Epoch 3/100
16/16 [==============================] - 0s 5ms/step - loss: 15.5696
Epoch 4/100
16/16 [==============================] - 0s 3ms/step - loss: 13.3737
Epoch 5/100
16/16 [==============================] - 0s 3ms/step - loss: 15.7502
Epoch 6/100
16/16 [==============================] - 0s 4ms/step - loss: 15.4767
Epoch 7/100
16/16 [==============================] - 0s 4ms/step - loss: 15.2557
Epoch 8/100
16/16 [==============================] - 0s 3ms/step - loss: 15.0357
Epoch 9/100
16/16 [==============================] - 0s 3ms/step - loss: 14.7955
Epoch 10/100
16/16 [==============================] - 0s 4ms/step - loss: 16.3959
Epoch 11/100
16/16 [==============================] - 0s 5ms/step - loss: 16.2154
Epoch 12/100
16/16 [==============================] - 0s 4ms/step - loss: 14.0689
Epoch 13/100
16/16 [=====

16/16 [==============================] - 0s 3ms/step - loss: 14.1667


In [7]:
# 4. 모델 이용
print(model.predict(cause[:5]))
print(effect[:5])

[[28.481287]
 [24.063768]
 [29.099   ]
 [29.68756 ]
 [29.729101]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [9]:
# iris 품종분류

In [10]:
# 데이터 준비
url_iris = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
ir = pd.read_csv(url_iris)

#원핫인코딩
ir = pd.get_dummies(ir)

ir.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [15]:
# 종속변수, 독립변수 나누기
cause = ir[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
effect = ir[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(cause.shape, effect.shape)

(150, 4) (150, 3)


In [16]:
#2. 모델의 구조 만들기
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(3, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [17]:
#모델 구조 확인
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_7 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_10 (Dense)             (None, 3)                 27        
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 12        
Total params: 223
Trainable params: 223
Non-trainable params: 0
_____________________________________________________________

In [18]:
#3. 데이터 모델 학습(FIT)
model.fit(cause, effect, epochs=100)

Epoch 1/100
5/5 [==============================] - 2s 2ms/step - loss: 1.1331 - accuracy: 0.3867
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0969 - accuracy: 0.5533
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0665 - accuracy: 0.5333
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0356 - accuracy: 0.5000
Epoch 5/100
5/5 [==============================] - 0s 5ms/step - loss: 1.0042 - accuracy: 0.5733
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9740 - accuracy: 0.6533
Epoch 7/100
5/5 [==============================] - 0s 7ms/step - loss: 0.9442 - accuracy: 0.7533
Epoch 8/100
5/5 [==============================] - 0s 5ms/step - loss: 0.9153 - accuracy: 0.8267
Epoch 9/100
5/5 [==============================] - 0s 5ms/step - loss: 0.8889 - accuracy: 0.8800
Epoch 10/100
5/5 [==============================] - 0s 5ms/step - loss: 0.8636 - accuracy: 0.8533
Epoch 11/100
5/5 [===========

5/5 [==============================] - 0s 5ms/step - loss: 0.0880 - accuracy: 0.9867
Epoch 84/100
5/5 [==============================] - 0s 4ms/step - loss: 0.0868 - accuracy: 0.9800
Epoch 85/100
5/5 [==============================] - 0s 5ms/step - loss: 0.0886 - accuracy: 0.9800
Epoch 86/100
5/5 [==============================] - 0s 3ms/step - loss: 0.0844 - accuracy: 0.9800
Epoch 87/100
5/5 [==============================] - 0s 7ms/step - loss: 0.0835 - accuracy: 0.9867
Epoch 88/100
5/5 [==============================] - 0s 4ms/step - loss: 0.0858 - accuracy: 0.9800
Epoch 89/100
5/5 [==============================] - 0s 4ms/step - loss: 0.0795 - accuracy: 0.9867
Epoch 90/100
5/5 [==============================] - 0s 3ms/step - loss: 0.0788 - accuracy: 0.9800
Epoch 91/100
5/5 [==============================] - 0s 3ms/step - loss: 0.0798 - accuracy: 0.9867
Epoch 92/100
5/5 [==============================] - 0s 3ms/step - loss: 0.0799 - accuracy: 0.9800
Epoch 93/100
5/5 [===============

In [19]:
#4. 모델을 이용
print(model.predict(cause[0:5]))
print(effect[0:5])
#9.99 * 10((-1)) -> 1에 가까운 숫자

[[9.99847770e-01 1.11438036e-04 4.07151929e-05]
 [9.99677777e-01 2.31024300e-04 9.11191310e-05]
 [9.99757111e-01 1.73929904e-04 6.90136003e-05]
 [9.99651909e-01 2.47182732e-04 1.00937999e-04]
 [9.99856353e-01 1.05785584e-04 3.77536708e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
